TestMVC/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
    }
}

TestMVC/Models/UserData.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string City { get; set; }
        public string Remark { get; set; }
    }
}

TestMVC/Controllers/UsersController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestMVC.Models;
using TestMVC.ViewModel;

namespace TestMVC.Controllers
{
    public class UsersController : Controller
    {
        private Test_MVCEntities _context;
        public UsersController()
        {
            _context = new Test_MVCEntities();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
        // GET: Users
        public ActionResult Index()
        {
            //var users = _context.Users.Where(m=>m.IsActive == false).OrderBy(c => c.ID).ToList();
            var users = new List<User>();
            UsersViewModel usersViewModel = new UsersViewModel();
            usersViewModel.Name = "";
            //usersViewModel.UsersView = users;
            if (TempData["Error"] != null)
            {
                ViewBag.Message = TempData["Error"].ToString();
                if (TempData["Error"].ToString() == "Active")
                {
                    users = _context.Users.Where(m => m.IsActive == true).OrderBy(c => c.ID).ToList();
                    usersViewModel.UsersView = users;
                }
                else
                {
                    users = _context.Users.Where(m => m.IsActive == false).OrderBy(c => c.ID).ToList();
                    usersViewModel.UsersView = users;
                }
            }
            else
            {
                users = _context.Users.Where(m => m.IsActive == false).OrderBy(c => c.ID).ToList();
                usersViewModel.UsersView = users;
            }
            
            return View(usersViewModel);
        }
        
        public ActionResult Update(UsersViewModel usersViewModel, string Save,string Active, string InActive, string Update, List<string> checkUser, FormCollection collection)
        {
            if (!string.IsNullOrEmpty(Save))
            {
                if (!ModelState.IsValid)
                {
                    TempData["Error"] = "please provide name";
                    return RedirectToAction("Index");
                }
                User user = new User();
                user.ID = 0;
                user.Name = usersViewModel.Name;
                user.IsActive = false;
                _context.Users.Add(user);
                _context.SaveChanges();
                TempData["Error"] = "Detail Saved";
                return RedirectToAction("Index");
            }
            if (!string.IsNullOrEmpty(Active))
            {
                TempData["Error"] = "Active";
                return RedirectToAction("Index");
            }
            if (!string.IsNullOrEmpty(InActive))
            {
                TempData["Error"] = "InActive";
                return RedirectToAction("Index");
            }
            if (!string.IsNullOrEmpty(Update))
            {
                if (string.IsNullOrEmpty(Request.Form["AllUser"]))
                {
                    TempData["Error"] = "No User Available";
                    return RedirectToAction("Index");
                }
                string strSelected = "0";
                if (!string.IsNullOrEmpty(Request.Form["checkUser"]))
                {
                    //TempData["Error"] = "Please Select Users for Activation";
                    //return RedirectToAction("Index");
                    strSelected = Request.Form["checkUser"];
                }
               
                string strAll = Request.Form["AllUser"];

                string[] arrChecked = strSelected.Split(',');
                string[] arrUserAll = strAll.Split(',');
                ArrayList arrListUnChecked = new ArrayList();
                ArrayList arrListChecked = new ArrayList();

                for (int i = 0; i < arrUserAll.Count(); i++)
                {
                    arrListUnChecked.Add(Convert.ToInt32(arrUserAll[i]));
                }
                //if (!string.IsNullOrEmpty(strSelected))
                //{

                //}
                for (int i = 0; i < arrChecked.Count(); i++)
                {
                    arrListChecked.Add(Convert.ToInt32(arrChecked[i]));
                    arrListUnChecked.Remove(Convert.ToInt32(arrChecked[i]));
                }
                arrListChecked.Remove(0);
                foreach (int id in arrListChecked)
                {
                    var userInDb = _context.Users.Where(m => m.ID == id).SingleOrDefault();
                    if (userInDb.IsActive != true)
                    {
                        userInDb.IsActive = true;
                    }
                }

                foreach (int id in arrListUnChecked)
                {
                    var userInDb = _context.Users.Where(m => m.ID == id).SingleOrDefault();
                    if (userInDb.IsActive != false)
                    {
                        userInDb.IsActive = false;
                    }
                }

                _context.SaveChanges();
                TempData["Error"] = "Details Updated";
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        public ActionResult UserData()
        {
            var userData = _context.UserDatas.ToList();
            //UserDataViewModel userDataViewModel = new UserDataViewModel(userData);
            return View("UserData", userData);
        }

        public ActionResult UpdateUserData(IEnumerable<UserData> userData)
        {
            if (userData != null)
            {
                foreach (var user in userData)
                {
                    int id = user.ID;
                    string name = user.Name;
                }
            }
            return RedirectToAction("UserData");
        }
    }
}

TestMVC/Views/Users/Index.cshtml
@model TestMVC.ViewModel.UsersViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Users</h2>
@using (Html.BeginForm("Update", "Users", FormMethod.Post))
{
        <div class="row">
            <div class="col-lg-3">
                <div class="form-group">
                    @Html.TextBoxFor(m => m.Name)
                </div>
            </div>
            <div class="col-lg-4">
                <button type="submit" id="btn_submit" value="Save" name="Save" class="btn btn-success">Save</button>
            </div>
            <div class="col-lg-3">
                @ViewBag.Message
            </div>
        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-lg-6">
                <table class="table table-bordered table-hover">
                    <tr>
                        <th>ID</th>
                        <th>Is Active</th>

                    </tr>

                    @foreach (var user in Model.UsersView)
                    {
                        <tr>
                            <td>@Html.DisplayFor(x => user.ID)</td>
                            <td><input type="checkbox" name="checkUser" value="@user.ID" checked="@user.IsActive" /><input type="checkbox" hidden="hidden" name="AllUser" value="@user.ID" checked="checked" />@user.Name</td>
                        </tr>

                    }

                </table>
                <br />
                <br />
                <button type="submit" id="btn_submit" value="InActive" name="InActive" class="btn btn-success">In-Active users</button>
                <button type="submit" id="btn_submit" value="Active" name="Active" class="btn btn-success">Active users</button>
                <button type="submit" id="btn_submit" value="Update" name="Update" class="btn btn-success">Update</button>
            </div>
        </div>
    
}

TestMVC/Views/Users/UserData.cshtml
@model IEnumerable<TestMVC.Models.UserData>
@{
    ViewBag.Title = "UserData";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>UserData</h2>

@using (Html.BeginForm("UpdateUserData", "Users", FormMethod.Post))
{
    <div class="row">
        <table class="table table-bordered table-hover">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Email</th>
                <th>User Name</th>
                <th>City</th>
                <th>Remark</th>
                <th>Update</th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(x => item.ID)</td>
                    <td>@Html.DisplayFor(x => item.Name)</td>
                    <td>@Html.DisplayFor(x => item.Email)</td>
                    <td>@Html.DisplayFor(x => item.UserName)</td>
                    <td>@Html.DisplayFor(x => item.City)</td>
                    <td>@Html.TextBoxFor(x => item.Remark, new { id = "box"+@item.ID+""})</td>
                    <td><button type="submit" id="btn_submit+@item.ID" value="btn+@item.ID" onclick="testFunc(@item.ID);" name="Update+@item.ID" class="btn btn-success">Update</button></td>
                </tr>
            }
        </table>
    </div>
}
@section scripts
{
    <script>
        $(document).ready(function () {
            //$("#btn_submit").click(function () {
            //    event.preventDefault();
            //    var id1 = $('#btn_submit').val();
            //    alert("Selected: " + id1)
            //});
        });

        function testFunc(id) { 
            event.preventDefault();
            var boxName = "box" + id;
            var id1 = $('#box'+id).val();
            alert("Selected: " + id1)
            } 


    </script>
}