TestMVC/Controllers/UserEditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TestMVC.Models;

namespace TestMVC.Controllers
{
    public class UserEditController : Controller
    {
        private Test_MVCEntities _context;
        public UserEditController()
        {
            _context = new Test_MVCEntities();
        }
        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET: UserEdit
        public ActionResult Index()
        {
            var users = _context.Users.OrderBy(c => c.ID).ToList();
            return View("Edit",users);
        }

        public ActionResult Edit(List<User> userList)
        {
            foreach (var user in userList)
            {
                var userInDb = _context.Users.Where(m => m.Name == user.Name).SingleOrDefault();
                if (userInDb.IsActive != user.IsActive)
                {
                    userInDb.IsActive = user.IsActive;
                }
            }

            _context.SaveChanges();
            TempData["Error"] = "Details Updated";
            return RedirectToAction("Index");
        }
    }
}

TestMVC/Views/UserEdit/Edit.cshtml
@model IEnumerable<TestMVC.Models.User>
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "UserEdit", FormMethod.Post))
{

    <div class="row">
        <div class="col-lg-6">
            <table class="table table-bordered table-hover">
                <tr>
                    <th>ID</th>
                    <th>Is Active</th>
                    <th>Users</th>
                </tr>

                @foreach (var user in Model)
                {
                    <tr>
                        <td>@Html.TextBoxFor(x => user.ID)</td>
                        <td></td>
                        <td>@Html.TextBoxFor(x => user.Name, new { @class = "form-control", id = "dsfdsjhk" })</td>
                    </tr>

                }

            </table>
            <div class="col-lg-12">
                <div class="col-lg-4">
                    <select class="form-control" id="carType">
                        <option value="Volvo">Volvo</option>
                        <option value="Saab">Saab</option>
                        <option value="Mercedes">Mercedes</option>
                        <option value="Audi">Audi</option>
                    </select>
                </div>
                <div class="col-lg-4">
                    <input type="text" placeholder="Please User Name" autocomplete="off" id="txtUserNames" class="form-control" />
                </div>
                <div class="col-lg-4">
                    <input type="text" placeholder="Second Type ahead" autocomplete="off" id="txtTypeTest" class="form-control" />
                </div>
            </div>
            @Html.ActionLink("Document", "Index", "Document", new { file = "11111.docx" }, null)
            <br />
            <br />
            <button type="submit" id="btn_submit" value="Update" name="Update" class="btn btn-success">Update</button>
        </div>
    </div>

}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {
            //var listUsers
            var users = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('Name'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                //prefetch: '../data/films/post_1960.json',
                remote: {
                    url: '/Json/AllUsers/%QUERY',
                    wildcard: '%QUERY'
                }
            });

            $('#txtUserNames').typeahead({
                minLength: 2,
                highlight: true
            }, {
                limit: 20,
                name: 'areaNames25',
                display: 'Name',
                source: users
            }).on('typeahead:selected', function (e, response1) {
                var areaID = response1.Name;
                alert("Selected: " + areaID)
            });

            // second type ahead test

            var states = ['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
                'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii',
                'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
                'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
                'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
                'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota',
                'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island',
                'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont',
                'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming'
            ];

            var substringMatcher = function (strs) {
                return function findMatches(q, cb) {
                    var matches, substringRegex;

                    // an array that will be populated with substring matches
                    matches = [];

                    // regex used to determine if a string contains the substring `q`
                    substrRegex = new RegExp(q, 'i');

                    // iterate through the pool of strings and for any string that
                    // contains the substring `q`, add it to the `matches` array
                    $.each(strs, function (i, str) {
                        if (substrRegex.test(str)) {
                            matches.push(str);
                        }
                    });

                    cb(matches);
                };
            };

            var secondTest = new Bloodhound({
                datumTokenizer: Bloodhound.tokenizers.obj.whitespace('Name'),
                queryTokenizer: Bloodhound.tokenizers.whitespace,
                //prefetch: '../data/films/post_1960.json',
                remote: {
                    url: '/Json/AllUsersSecond/%EQUIPMENT,%QUERY',
                    replace: function (url) {
                        return url.replace('%EQUIPMENT', $("#carType option:selected").val()).replace('%QUERY', $('#txtTypeTest').val());
                    },
                    wildcard: '%QUERY'
                }
            });

            $('#txtTypeTest').typeahead({
                minLength: 1,
                highlight: true
            }, {
                limit: 20,
                name: 'typeTest',
                display: 'Name',
                source: secondTest //substringMatcher(states)
            }).on('typeahead:selected', function (e, response1) {
                var areaID = response1.Name;
                alert("Selected: " + areaID)
            });
        });

        function AjaxCall(url, data, type) {
            return $.ajax({
                url: url,
                type: type ? type : 'GET',
                data: data,
                contentType: 'application/json'
            });
        }
    </script>
}